export type TCentralEventDTO =
  | 'UNION_OT'
  | 'SCHOOL_OT'
  | 'CORE_DAY'
  | 'UNION_NETWORKING_DAY'
  | 'IDEATHON'
  | 'NEORDINARY_HACKATHON'
  | 'UMC_HACKATHON'
  | 'SCHOOL_HACKATHON'
  | 'UMC_DEMO_DAY'
  | 'NEORDINARY_DEMO_DAY';
